name: Bug report
description: Create a report to help us improve
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "If your issue relates to a particular puzzle, make sure to remember to add the corresponding label to the issue."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior:"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "![DESCRIPTION](LINK.png)"
    validations:
      required: false
  - type: textarea
    id: files
    attributes:
      label: "Puzzle Files"
      description: "If applicable, add any puzzle files to help explain your problem."
      placeholder: You will need to zip up the puzzle files before you can attach them to your issue.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
    validations:
      required: false
