---
name: Bug report
description: Create a report to help us improve
title: "[ISSUE] "
labels: bug

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Files**
If applicable, add any puzzle files that demonstrate your problem.

**Additional context**
Add any other context about the problem here.
