name: Enhancement request
description: Improve an already-existing feature
title: "[ENHANCEMENT] <description>"
labels: [ enhancement ]
body:
  - type: textarea
    id: current_behavior
    attributes:
      label: "Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem."
      description: "A clear and concise description of the current behavior and problem."
      placeholder: "Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the improvement you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
