name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] <description>"
  <<<<<<< HEAD
labels: [ new feature ]
  =======
labels: [ enhancement, new feature ]
  >>>>>>> b28ba6c38166142ecd457ffee2797fffc89a51b4
body:
  - type: textarea
    id: description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
