# Documentation for format found at https://www.formdev.com/flatlaf/properties-files


# Overrides of default flatlaf\FlatLaf.properties

TabbedPane.rotateTabRuns = false


# Base LEGUP properties that other themes inherit from

# Variables
@valid = #64DD17
@invalid = #F44336
@indicator1 = #3464EB
@indicator2 = #DD8717

defaultFont = Roboto-Regular, 12

# Legup
Legup.font = +2
Legup.infoFont = $Legup.font
Legup.errorFont = italic $Legup.font
Legup.infoColor = @foreground
Legup.errorColor = @invalid

# Puzzle
Puzzle.foreground = #212121
Puzzle.font = bold 16 "Times Roman"
Puzzle.valid = @valid
Puzzle.invalid = @invalid
Puzzle.hover = #7986CB
Puzzle.case = #1A237E
# Indicators for rule examples
Puzzle.indicator1 = @indicator1
Puzzle.indicator2 = @indicator2

# Tree
Tree.outline = #212121
Tree.outlineWidth = 3
Tree.default = #FFEB3B
Tree.arrowDefault = #808080
Tree.contradiction = #B20A10
Tree.selected = #1E88E5
Tree.selectedOutline = lighten($Tree.selected, 10%)
Tree.selectedWidth = 2
Tree.hover = $Puzzle.hover
Tree.hoverOutline = lighten($Tree.hover, 10%)
