
# Documentation for format found at https://www.formdev.com/flatlaf/properties-files


# Base LEGUP properties that other themes inherit from

# Variables
@valid = #64DD17
@invalid = #F44336
@hover = #7986CB
@indicator1 = #3464EB
@indicator2 = #DD8717

# Puzzle
Puzzle.valid = @valid
Puzzle.invalid = @invalid
Puzzle.hover = @hover
Puzzle.case = #1A237E
# Indicators for highlighting in rule examples
Puzzle.indicator1 = @indicator1
Puzzle.indicator2 = @indicator2
# General styling for all puzzles though many have independently set styling
Puzzle.foreground = #212121
Puzzle.background = @background
Puzzle.font = bold 16 "Times Roman"
Puzzle.borderColor = $Puzzle.foreground
Puzzle.borderWidth = 1
Puzzle.highlightWidth = 2

# Tree
Tree.valid = @valid
Tree.invalid = @invalid
Tree.outline = #212121
Tree.outlineWidth = 3
Tree.default = #FFEB3B
Tree.arrowDefault = #808080
Tree.contradiction = #B20A10
Tree.selected = #1E88E5
Tree.selectedOutline = lighten($Tree.selected, 10%)
Tree.selectedWidth = 2
Tree.hover = $Puzzle.hover
Tree.hoverOutline = lighten($Tree.hover, 10%)


# Styles for individual puzzle types

# Battleship
Battleship.unknown = #E0E0E0
Battleship.water = #1565C0
Battleship.ship = #757575
Battleship.unrecognized = #E040FB
Battleship.text = #FFEB3B
Battleship.font = -6 $Puzzle.font
Battleship.clue = #000
Battleship.clueFont = $Puzzle.font
Battleship.borderColor = #212121
Battleship.borderWidth = 1

# Binary
Binary.background = #FFF
Binary.given = #75757580
Binary.text = $Puzzle.foreground
Binary.font = +1 $Puzzle.font
Binary.borderColor = #000
Binary.unknownBorderWidth = 0
Binary.knownBorderWidth = 1

# Fillapix
Fillapix.black = #212121
Fillapix.white = #F5F5F5
Fillapix.unknown = #9E9E9E
Fillapix.font = $Puzzle.font
Fillapix.borderColor = #000
Fillapix.borderWidth = 1

# Heyawake
Heyawake.black = #212121
Heyawake.white = #F5F5F5
Heyawake.unknown = #9E9E9E
Heyawake.font = $Puzzle.font
Heyawake.borderColor = $Heyawake.black
Heyawake.cellBorderWidth = 1
Heyawake.regionBorderWidth = 3

# LightUp
LightUp.light = #FFF176
LightUp.black = #212121
LightUp.white = #F5F5F5
LightUp.unknown = #9E9E9E
LightUp.font = $Puzzle.font

# Masyu
Masyu.background = #C6C6C6
Masyu.black = #000
Masyu.white = #FFF
Masyu.line = #000
Masyu.lineWidth = 3
Masyu.borderColor = $Masyu.black
Masyu.borderWidth = 1

# Minesweeper
Minesweeper.background = #CBCBCB
Minesweeper.font = $Puzzle.font
Minesweeper.borderColor = #000
Minesweeper.borderWidth = 1
# Colors for each value a tile can be
Minesweeper.color1 = #0703FB
Minesweeper.color2 = #077B03
Minesweeper.color3 = #FF0303
Minesweeper.color4 = #00007D
Minesweeper.color5 = #870303
Minesweeper.color6 = #078383
Minesweeper.color7 = #070303
Minesweeper.color8 = #878383

# Nurikabe
Nurikabe.white = #FFF
Nurikabe.black = #000
Nurikabe.unknown = #C0C0C0
Nurikabe.text = $Nurikabe.black
Nurikabe.font = $Puzzle.font
Nurikabe.borderColor = #000
Nurikabe.borderWidth = 1

# ShortTruthTable
ShortTruthTable.true = spin(saturate(darken(@valid, 15%), 37%), 23)
ShortTruthTable.false = spin(saturate(darken(@invalid, 24%), 22%), -4)
ShortTruthTable.unknown = #FFF
ShortTruthTable.text = #000
ShortTruthTable.font = $Puzzle.font

# Skyscrapers
Skyscrapers.background = #EEE
Skyscrapers.clue = #000
Skyscrapers.text = #212121
Skyscrapers.font = $Puzzle.font
Skyscrapers.borderColor = #424242
Skyscrapers.borderWidth = 1

# StarBattle
StarBattle.foreground = #000
StarBattle.background = #FFF
StarBattle.unknown = #C0C0C0
StarBattle.borderColor = #000
StarBattle.cellBorderWidth = 1
StarBattle.regionBorderWidth = 3

# Sudoku
Sudoku.background = #EEE
Sudoku.case = $Puzzle.case
Sudoku.given = #75757580
Sudoku.text = #212121
Sudoku.font = $Puzzle.font
Sudoku.annotateFont = 50% $Puzzle.font
Sudoku.borderColor = #424242
Sudoku.minorBorderWidth = 1
Sudoku.majorBorderWidth = 4

# Thermometer
Thermometer.text = #000
Thermometer.font = $Puzzle.font
Thermometer.borderColor = #000
Thermometer.borderWidth = 1

# TreeTent
TreeTent.unknown = #C0C0C0
TreeTent.text = #000
TreeTent.font = $Puzzle.font
TreeTent.line = #FFF
TreeTent.lineWidth = 2
TreeTent.borderColor = #000
TreeTent.knownBorderWidth = 0
TreeTent.unknownBorderWidth = 1


# SVG expected values

Expected.Puzzle.valid = #64DD17
Expected.Puzzle.invalid = #F44336
Expected.Puzzle.hover = #7986CB
Expected.Puzzle.case = #1A237E
Expected.Puzzle.indicator1 = #3464EB
Expected.Puzzle.indicator2 = #DD8717
Expected.Puzzle.foreground = #212121
Expected.Puzzle.background = #F2F2F2
Expected.Puzzle.text = #222222
Expected.Puzzle.borderColor = #232323


# Styles for various UI elements

[style]Label.welcome = font: 17 bold; border: 0,0,0,5;
[style]Label.version = font: 10 italic; border: 0,0,0,5;
[style]Label.info = font: {font} 14; foreground: @foreground; background: @background; border: 5,15,5,15,mix(@foreground,@background,25%),3,10;
[style]Label.error = font: 14 italic; foreground: @invalid; background: @background; border: 5,15,5,15,mix(@invalid,@background,25%),3,10;
[style]Label.prefsHeading = font: 14 bold;
[style]Label.zoomer = font: {font} 16;

[style]Button.rule = font: 12 "Segoe UI";
[style]Button.smallRule = font: 10 "Segoe UI";

[style]PopupMenu.dataSelection = background: #808080;


# Overrides of default flatlaf\FlatLaf.properties

defaultFont = Roboto-Regular, 12
TabbedPane.rotateTabRuns = false